# Generated by Django 4.2.4 on 2024-10-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('userid', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='karyawan/')),
            ],
        ),
    ]
