# Generated by Django 4.2.4 on 2024-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
