# Generated by Django 4.2.4 on 2024-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_absen_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='photo',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
