# Generated by Django 4.2.4 on 2024-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_karyawan_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
